### ISSUE TITLE
"ImportError: cannot import name Marker" upon rwt_moveit

### ISSUE THREAD

**Issue by 130s** [tork-a/visualization_rwt#36]
From @dylanvaughn.

---

I'm still having trouble getting the visualization app working.  I am able to get the rviz / moveit planning running, i.e. 

```
$ roslaunch vs060_moveit_config demo_simulation_noenvironment.launch
```

(note: your instructions say to use the 'demo_simulation.launch' file but I think you renamed that here:
https://github.com/start-jsk/denso/commit/d789dd89a883667a9ce05238fd6081bd33f05965)

This seems to work.

However, when I run the second command:

```
$ roslaunch rwt_moveit sim_demo.launch
```

it seems to most work but there are some exceptions in the output about not being able to import Marker:

```

process[start_interactive_moveit-12]: started with pid [26426]
[INFO] [WallTime: 1410070039.770166] Rosbridge WebSocket server started on port 9090
process[goal_interactive_moveit-13]: started with pid [26446]
Traceback (most recent call last):
  File "/home/dylan/catkin_ws/src/visualization_rwt/rwt_moveit/nodes/interactive_moveit.py", line 13, in <module>
    from interactive_markers.interactive_marker_server import (
ImportError: cannot import name Marker
process[start_marker_proxy-14]: started with pid [26480]
Traceback (most recent call last):
  File "/home/dylan/catkin_ws/src/visualization_rwt/rwt_moveit/nodes/interactive_moveit.py", line 13, in <module>
    from interactive_markers.interactive_marker_server import (
ImportError: cannot import name Marker
process[goal_marker_proxy-15]: started with pid [26504]
[start_interactive_moveit-12] process has died [pid 26426, exit code 1, cmd /home/dylan/catkin_ws/src/visualization_rwt/rwt_moveit/nodes/interactive_moveit.py __name:=start_interactive_moveit __log:=/home/dylan/.ros/log/97d9e2ea-3654-11e4-bb3f-f8d1115e8537/start_interactive_moveit-12.log].
log file: /home/dylan/.ros/log/97d9e2ea-3654-11e4-bb3f-f8d1115e8537/start_interactive_moveit-12*.log
process[link_group-16]: started with pid [26551]
[goal_interactive_moveit-13] process has died [pid 26446, exit code 1, cmd /home/dylan/catkin_ws/src/visualization_rwt/rwt_moveit/nodes/interactive_moveit.py __name:=goal_interactive_moveit __log:=/home/dylan/.ros/log/97d9e2ea-3654-11e4-bb3f-f8d1115e8537/goal_interactive_moveit-13.log].
log file: /home/dylan/.ros/log/97d9e2ea-3654-11e4-bb3f-f8d1115e8537/goal_interactive_moveit-13*.log
process[roswww-17]: started with pid [26560]
No handlers could be found for logger "rosout"
[link_group-16] process has finished cleanly
log file: /home/dylan/.ros/log/97d9e2ea-3654-11e4-bb3f-f8d1115e8537/link_group-16*.log
```

Then when I go to the site there seem to be many missing files (see screenshot) - I have seen some of these files in other packages but am unsure how to link them all together.  I looked in this file:

https://github.com/tork-a/rwt_ros/blob/hydro-devel/roswww/src/roswww/webserver.py

which seems to be loading up different packages and making them available at various URIs but haven't figured it out yet.  I tried manually creating the lib/ros3djs folder and copying the resources over which helped a little but the vs060 mesh files then were all 404ing, which makes me think I am doing something wrong.

**Comment by 130s** [comment]
For Marker issue, is `interactive_marker_proxy` installed?

```
$ sudo apt-get install ros-hydro-interactive-marker-proxy
```

**Comment by 130s** [comment]
Fixed by https://github.com/tork-a/visualization_rwt/pull/40
