### ISSUE TITLE
[rwt_image_view] resolving type in parallel

### ISSUE THREAD

**Issue by garaemon** [tork-a/visualization_rwt#9]

**Comment by garaemon** [comment]
rosapiに問題がある?
`/rosapi/topic_type`を並列に何度も呼び出すことが難しいらしい

```
[ERROR] [WallTime: 1382376050.720365] [31.621000] Error processing request: 
None
Traceback (most recent call last):
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 619, in _handle_request
    response = convert_return_to_response(self.handler(request), self.response_class)
  File "/opt/ros/groovy/lib/rosapi/rosapi", line 85, in get_topic_type
    return TopicTypeResponse(proxy.get_topic_type(request.topic))
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rosapi/proxy.py", line 69, in get_topic_type
    for x in get_published_topics():
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rospy/client.py", line 370, in get_published_topics
    code, msg, val = get_master().getPublishedTopics(namespace)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rospy/msproxy.py", line 101, in wrappedF
    return f(*args, **kwds)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
Traceback (most recent call last):
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1289, in single_request
    self.send_request(h, handler, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1391, in send_request
    connection.putrequest("POST", handler, skip_accept_encoding=True)
  File "/usr/lib/python2.7/httplib.py", line 856, in putrequest
    raise CannotSendRequest()
CannotSendRequest

```

**Comment by garaemon** [comment]
abandoned
